apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
{{ include "common.instance-name" . | indent  4 }}
  ports:
    - port: {{ default 80 .Values.port }}
      targetPort: {{ default 80 .Values.port }}
